### ISSUE TITLE
Remove personal paths

### ISSUE THREAD

**Issue by iamgp** [Pfizer-BradleyBare/PytomatedLiquidHandling#1]
https://github.com/Pfizer-BradleyBare/PytomatedLiquidHandling/blob/266ea4a0af6ece6ed0eb6c3afc7a002dae0c5486/.vscode/settings.json#L2

Hi,
Quick suggestion that I noticed during looking through your repo, you have personal paths in the vscode settings for your venv python path, you may want to remove this?

**Comment by Pfizer-BradleyBare** [comment]
Good call. I removed the .vscode folder and added to .gitignore.

Thanks!
